config/routes.rb
Rails.application.routes.draw do

  get 'posts/index'

  root 'home#welcome'

  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates_presence_of :content, :title, message: "不能为空"
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  attr_accessor :password, :password_confirmation

  has_many :posts

  validates_presence_of :email, message: "邮箱不能为空"
  validates_format_of :email, message: "邮箱格式不正确",
    with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/,
    if: proc { |user| !user.email.blank? }
  validates_presence_of :password, message: "密码不能为空",
    if: :need_validate_pw
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
    if: :need_validate_pw
  validates_confirmation_of :password, message: "密码不一致",
    if: :need_validate_pw
  validates_length_of :password, message: "密码最短为6位", minimum: 6,
    if: :need_validate_pw

  private
  def need_validate_pw
    self.new_record? || (!password.nil? || !password_confirmation.nil?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.view_count = 0
    @post.category_id = 1

    if @post.save
      flash[:notice] = "文章保存成功"
      redirect_to @post
    else
      flash[:alert] = "文章保存失败"
      render action: :new
    end
  end

  def edit
  end

  def update
    if @post.save
      @posts = current_user.reload.posts
      flash[:notice] = "文章修改成功"
      redirect_to @posts
    else
      flash[:alert] = "文章修改失败"
      render action: :edit
    end
  end

  def destroy
    @post.destroy

    @posts = current_user.reload.posts
    render action: :index
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if user = login(params[:email], params[:password])
      flash[:notice] = "登陆成功！"
      redirect_to root_path
    else
      flash[:alert] = "邮箱或密码不正确"
      redirect_to new_session_path
    end
  end

  def destroy
    logout
    flash[:notice] = "退出成功！"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      flash[:alert] = "注册成功"
      redirect_to new_session_path
    else
      render action: :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper

  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <% debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="col-md-12">
  <%= simple_form_for @post do |f| %>
    <div class="form-group">
      <div class="row">
        <div class="col-md-10">
          <%= f.input :title, label: false, input_html: { class: "form-control", placeholder: "在这里输入标题"} %>
        </div>
        <div class="col-md-2">
          <button class="btn btn-default dropdown-toggle pull-left" type="button" id="category" data-toggle="dropdown">文章类别
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="category">
            <li><a role="menu" tabindex= "-1" href="#">转载</a></li>
            <li class="active"><a role="menu" tabindex="-1" href="#">原创</a></li>
            <li class="divider"></li>
            <li class="disabled"><a role="menu" tabindex="-1" href="#">翻译</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.input :content, as: :text, label: false, input_html: { rows: 15, class: "form-control"} %>
    </div>
    <div class="form-froup pull-right">
      <%= f.button :submit, "保存" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h2 class="text-center"> 编辑文章 </h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<h2>文章列表</h2>
<table class="table table-hover">
  <tbody>
    <% @posts.each do |p| %>
      <tr>
        <td>默认</td>
        <td><%= link_to p.title, post_path(p.id) %> <%= p.updated_at.to_date %></td>
        <td>阅读 <%= p.view_count%></td>
        <td>评论 0</td>
        <td>
          <%= link_to "编辑", edit_post_path(p) %>
          <%= link_to "删除", post_path(p), method: :delete, 'data-confirm': "确定要删除吗？" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h2 class="text-center"> 写新文章 </h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="text-center">
    <%= content_tag :h1, content_tag(:span, @post.title)%>
  </div>
  <div class="post-body">
    <%= content_tag :p, content_tag(:text_area, @post.content) %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container" style="margin-top:100px;">
  <p class="text-center">Copyright @2017 个人博客
    <br>Design by 
    <a href="http://www.baidu.com" target="_blank">李亚中</a>
  </p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href= "#" class="dropdown-toggle" data-toggle="dropdown">欢迎您，<%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "写文章", new_post_path %></li>
              <li><%= link_to "文章列表", posts_path %></li>
              <li><%= link_to "退出", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "注册", new_user_path %></li>
          <li><%= link_to "登陆", new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<h1>注册</h1>
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.messages.values.flatten.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :user, url: users_path, method: :post, html: { class: "form-horizontal", id: "user_form"} do |f| %>
  <div class="form-group">
    <div class="col-lg-12">邮箱 *</div>
    <div class="col-lg-12">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-12">密码 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-12">密码确认 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-12">
      <input type="submit" name="create_user_submit" value="创建用户", class="col-xs-12 btn btn-primary">
    </div>
  </div>
<% end%>